language: node_js
node_js:
  - "12.13.1"

before_install:
  - sudo apt-get update
  # - sudo apt-get -y install libxml2-dev

install:
  - npm install -g serverless@1.58.0

jobs:
  include:
    - stage: compile
      script: ./bin/compile.sh
    - stage: test
      script: ./bin/test.sh
    - stage: deploy
      if: branch = master
      script: ./bin/deploy.sh

stages:
  - compile
  - test
  - deploy
