language: node_js
node_js:
  - "12.13.1"

install:
  - bin/install.sh

jobs:
  include:
    #   - stage: build
    #     script: ./bin/build.sh
    - stage: deploy-pull-request
      script: bin/compile.sh && bin/deploy-pull-request.sh
    - stage: acceptance-test
      script: ./bin/acceptance-test.sh
    - stage: deploy
      script: ./bin/deploy.sh

stages:
  # - name: build # TODO: Use s3 for build artifacts and pass compiled code to other stages instead of recompiling
  - name: deploy
    if: branch = master AND type = push AND fork = false
  - name: deploy-pull-request
    if: type = pull_request
  - name: acceptance-test
    if: type = pull_request
