-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type BodyOfWater
    = BodyOfWater


type Color
    = Color


type Country
    = Country


type CountryTroopCounts
    = CountryTroopCounts


type Dimensions
    = Dimensions


type Game
    = Game


type GameConfiguration
    = GameConfiguration


type GameMap
    = GameMap


type GameWithoutMap
    = GameWithoutMap


type Map
    = Map


type Player
    = Player


type PlayerConfiguration
    = PlayerConfiguration


type PlayerTurn
    = PlayerTurn


type Point
    = Point


type Segment
    = Segment
