-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Game exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet String Api.Object.Game
id =
    Object.selectionForField "String" "id" [] Decode.string


map : SelectionSet decodesTo Api.Object.Map -> SelectionSet decodesTo Api.Object.Game
map object_ =
    Object.selectionForCompositeField "map" [] object_ identity


players : SelectionSet decodesTo Api.Object.Player -> SelectionSet (List decodesTo) Api.Object.Game
players object_ =
    Object.selectionForCompositeField "players" [] object_ (identity >> Decode.list)


neutralCountryTroops : SelectionSet decodesTo Api.Object.CountryTroopCounts -> SelectionSet (List decodesTo) Api.Object.Game
neutralCountryTroops object_ =
    Object.selectionForCompositeField "neutralCountryTroops" [] object_ (identity >> Decode.list)


playerTurn : SelectionSet decodesTo Api.Object.PlayerTurn -> SelectionSet decodesTo Api.Object.Game
playerTurn object_ =
    Object.selectionForCompositeField "playerTurn" [] object_ identity


currentUserPlayerId : SelectionSet String Api.Object.Game
currentUserPlayerId =
    Object.selectionForField "String" "currentUserPlayerId" [] Decode.string
