-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.GameConfiguration exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet String Api.Object.GameConfiguration
id =
    Object.selectionForField "String" "id" [] Decode.string


players : SelectionSet decodesTo Api.Object.PlayerConfiguration -> SelectionSet (List decodesTo) Api.Object.GameConfiguration
players object_ =
    Object.selectionForCompositeField "players" [] object_ (identity >> Decode.list)


mapId : SelectionSet String Api.Object.GameConfiguration
mapId =
    Object.selectionForField "String" "mapId" [] Decode.string


mapIdType : SelectionSet String Api.Object.GameConfiguration
mapIdType =
    Object.selectionForField "String" "mapIdType" [] Decode.string


joinToken : SelectionSet String Api.Object.GameConfiguration
joinToken =
    Object.selectionForField "String" "joinToken" [] Decode.string


currentUserPlayerId : SelectionSet String Api.Object.GameConfiguration
currentUserPlayerId =
    Object.selectionForField "String" "currentUserPlayerId" [] Decode.string


isCurrentUserHost : SelectionSet Bool Api.Object.GameConfiguration
isCurrentUserHost =
    Object.selectionForField "Bool" "isCurrentUserHost" [] Decode.bool
