-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PlayerConfiguration exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


color : SelectionSet decodesTo Api.Object.Color -> SelectionSet decodesTo Api.Object.PlayerConfiguration
color object_ =
    Object.selectionForCompositeField "color" [] object_ identity


playerId : SelectionSet String Api.Object.PlayerConfiguration
playerId =
    Object.selectionForField "String" "playerId" [] Decode.string


name : SelectionSet String Api.Object.PlayerConfiguration
name =
    Object.selectionForField "String" "name" [] Decode.string
