-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Segment exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


point1 : SelectionSet decodesTo Api.Object.Point -> SelectionSet decodesTo Api.Object.Segment
point1 object_ =
    Object.selectionForCompositeField "point1" [] object_ identity


point2 : SelectionSet decodesTo Api.Object.Point -> SelectionSet decodesTo Api.Object.Segment
point2 object_ =
    Object.selectionForCompositeField "point2" [] object_ identity
