-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.PlayerTurnStage exposing (..)

import Json.Decode as Decode exposing (Decoder)


type PlayerTurnStage
    = CapitolPlacement
    | TroopPlacement
    | AttackAnnexOrPort
    | TroopMovement
    | TroopMovementFromSelected
    | GameOver


list : List PlayerTurnStage
list =
    [ CapitolPlacement, TroopPlacement, AttackAnnexOrPort, TroopMovement, TroopMovementFromSelected, GameOver ]


decoder : Decoder PlayerTurnStage
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CapitolPlacement" ->
                        Decode.succeed CapitolPlacement

                    "TroopPlacement" ->
                        Decode.succeed TroopPlacement

                    "AttackAnnexOrPort" ->
                        Decode.succeed AttackAnnexOrPort

                    "TroopMovement" ->
                        Decode.succeed TroopMovement

                    "TroopMovementFromSelected" ->
                        Decode.succeed TroopMovementFromSelected

                    "GameOver" ->
                        Decode.succeed GameOver

                    _ ->
                        Decode.fail ("Invalid PlayerTurnStage type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PlayerTurnStage -> String
toString enum =
    case enum of
        CapitolPlacement ->
            "CapitolPlacement"

        TroopPlacement ->
            "TroopPlacement"

        AttackAnnexOrPort ->
            "AttackAnnexOrPort"

        TroopMovement ->
            "TroopMovement"

        TroopMovementFromSelected ->
            "TroopMovementFromSelected"

        GameOver ->
            "GameOver"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PlayerTurnStage
fromString enumString =
    case enumString of
        "CapitolPlacement" ->
            Just CapitolPlacement

        "TroopPlacement" ->
            Just TroopPlacement

        "AttackAnnexOrPort" ->
            Just AttackAnnexOrPort

        "TroopMovement" ->
            Just TroopMovement

        "TroopMovementFromSelected" ->
            Just TroopMovementFromSelected

        "GameOver" ->
            Just GameOver

        _ ->
            Nothing
